version: "3"

server:
  command: "php bin/console server:roadrunner"
  relay: pipes
http:
  address: "0.0.0.0:9201"
  middleware:
    - gzip
    - headers
  headers:
    cors:
      allowed_origin: "*"
      allowed_headers: "*"
      allowed_origin_regex: "^https?://.*"
      allowed_methods: "GET,POST,PUT,DELETE,OPTIONS"
      exposed_headers: "Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma"
      max_age: 600
      options_success_status: 200
      debug: false
  pool:
    debug: true
    num_workers: 1
    supervisor:
      max_worker_memory: 256
