version: '3'

status:
    address: '0.0.0.0:8081' # http://0.0.0.0:8081/health?plugin=http

server:
    command: 'php bin/console server:roadrunner'
    relay: pipes
http:
    address: '0.0.0.0:8080'
    middleware:
        - gzip
    pool:
        num_workers: 4
        supervisor:
            max_worker_memory: 256
