version: '3'

status:
    address: '0.0.0.0:9202' # http://0.0.0.0:8081/health?plugin=http

server:
    command: 'php bin/console server:roadrunner'
    relay: pipes
http:
    address: '0.0.0.0:9201'
    middleware:
        - gzip
    pool:
        num_workers: 0 # Means number of logical CPUs
        supervisor:
            max_worker_memory: 256 # 256MB memory limit per worker (Soft limit)
            exec_ttl: 60s # Maximum time a single job can run (Hard limit)
            ttl: 3600s # How long a worker can live (Soft limit)
