# Redis config stored as a configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: evekill-config
data:
  config.php: |-
    <?php

    return [
      'development' => true, // Tells Whoops to show errors or not
      'mongodb' => [
        'hosts' => [
          'evekill-mongodb-0.evekill-mongodb-headless.evekill.svc.cluster.local:27017',
          'evekill-mongodb-1.evekill-mongodb-headless.evekill.svc.cluster.local:27017',
          'evekill-mongodb-2.evekill-mongodb-headless.evekill.svc.cluster.local:27017',
        ]
      ],
      'redis' => [
        'host' =>'redis',
        'port' => 6379,
        'password' => '',
        'database' => 0,
      ],
      'meilisearch' => [
        'host' => 'meilisearch.evekill.svc.cluster.local:7700'
      ],
      'twig' => [
        'debug' => false,
        'autoReload' => true,
        'strictVariables' => false,
        'optimizations' => -1,
      ],
      'cloudflare' => [
        'token' => '',
      ],
      'fetcher' => [
        'user-agent' => 'EK/1.0',
      ],
      'esi' => [
        'user-agent' => 'EK/1.0',
        'global-rate-limit' => 500,
      ],
      'evewho' => [
        'user-agent' => 'EK/1.0',
        'rate-limit' => 10,
      ],
      'webhooks' => [
        'comments' => '{{ .Values.config.webhooks.comments }}',
        'esi-errors' => '{{ .Values.config.webhooks.esi_errors }}',
        'errors' => '{{ .Values.config.webhooks.errors }}',
      ]
    ];