<?php

namespace EK\Controllers;

use EK\Api\Abstracts\Controller;
use Psr\Http\Message\ResponseInterface;

class ESI extends Controller
{
    protected array $routes = [
        '/{version:latest|dev|v1}/alliances[/]' => ['GET'],
        '/{version:latest|dev|v1}/alliances/{alliance_id}/contacts/labels[/]' => ['GET'],
        '/{version:latest|dev|v1}/alliances/{alliance_id}/corporations[/]' => ['GET'],
        '/{version:latest|dev|v1}/alliances/{alliance_id}/icons[/]' => ['GET'],
        '/{version:latest|dev|v1}/characters/{character_id}/assets/names[/]' => ['POST'],
        '/{version:latest|dev|v1}/characters/{character_id}/attributes[/]' => ['GET'],
        '/{version:latest|dev|v1}/characters/{character_id}/calendar[/]' => ['GET'],
        '/{version:latest|dev|v1}/characters/{character_id}/calendar/{event_id}/attendees[/]' => ['GET'],
        '/{version:latest|dev|v1}/characters/{character_id}/contacts/labels[/]' => ['GET'],
        '/{version:latest|dev|v1}/characters/{character_id}/contracts[/]' => ['GET'],
        '/{version:latest|dev|v1}/characters/{character_id}/contracts/{contract_id}/bids[/]' => ['GET'],
        '/{version:latest|dev|v1}/characters/{character_id}/contracts/{contract_id}/items[/]' => ['GET'],
        '/{version:latest|dev|v1}/characters/{character_id}/fittings/{fitting_id}[/]' => ['DELETE'],
        '/{version:latest|dev|v1}/characters/{character_id}/fleet[/]' => ['GET'],
        '/{version:latest|dev|v1}/characters/{character_id}/fw/stats[/]' => ['GET'],
        '/{version:latest|dev|v1}/characters/{character_id}/implants[/]' => ['GET'],
        '/{version:latest|dev|v1}/characters/{character_id}/industry/jobs[/]' => ['GET'],
        '/{version:latest|dev|v1}/characters/{character_id}/killmails/recent[/]' => ['GET'],
        '/{version:latest|dev|v1}/characters/{character_id}/location[/]' => ['GET'],
        '/{version:latest|dev|v1}/characters/{character_id}/loyalty/points[/]' => ['GET'],
        '/{version:latest|dev|v1}/characters/{character_id}/mail[/]' => ['GET', 'POST'],
        '/{version:latest|dev|v1}/characters/{character_id}/mail/labels/{label_id}[/]' => ['DELETE'],
        '/{version:latest|dev|v1}/characters/{character_id}/mail/lists[/]' => ['GET'],
        '/{version:latest|dev|v1}/characters/{character_id}/mail/{mail_id}[/]' => ['DELETE', 'GET', 'PUT'],
        '/{version:latest|dev|v1}/characters/{character_id}/mining[/]' => ['GET'],
        '/{version:latest|dev|v1}/characters/{character_id}/opportunities[/]' => ['GET'],
        '/{version:latest|dev|v1}/characters/{character_id}/orders/history[/]' => ['GET'],
        '/{version:latest|dev|v1}/characters/{character_id}/planets[/]' => ['GET'],
        '/{version:latest|dev|v1}/characters/{character_id}/ship[/]' => ['GET'],
        '/{version:latest|dev|v1}/characters/{character_id}/wallet[/]' => ['GET'],
        '/{version:latest|dev|v1}/characters/{character_id}/wallet/transactions[/]' => ['GET'],
        '/{version:latest|dev|v1}/contracts/public/bids/{contract_id}[/]' => ['GET'],
        '/{version:latest|dev|v1}/contracts/public/items/{contract_id}[/]' => ['GET'],
        '/{version:latest|dev|v1}/contracts/public/{region_id}[/]' => ['GET'],
        '/{version:latest|dev|v1}/corporation/{corporation_id}/mining/extractions[/]' => ['GET'],
        '/{version:latest|dev|v1}/corporation/{corporation_id}/mining/observers[/]' => ['GET'],
        '/{version:latest|dev|v1}/corporation/{corporation_id}/mining/observers/{observer_id}[/]' => ['GET'],
        '/{version:latest|dev|v1}/corporations/{corporation_id}/assets/names[/]' => ['POST'],
        '/{version:latest|dev|v1}/corporations/{corporation_id}/bookmarks[/]' => ['GET'],
        '/{version:latest|dev|v1}/corporations/{corporation_id}/bookmarks/folders[/]' => ['GET'],
        '/{version:latest|dev|v1}/corporations/{corporation_id}/contacts/labels[/]' => ['GET'],
        '/{version:latest|dev|v1}/corporations/{corporation_id}/contracts[/]' => ['GET'],
        '/{version:latest|dev|v1}/corporations/{corporation_id}/contracts/{contract_id}/bids[/]' => ['GET'],
        '/{version:latest|dev|v1}/corporations/{corporation_id}/contracts/{contract_id}/items[/]' => ['GET'],
        '/{version:latest|dev|v1}/corporations/{corporation_id}/customs_offices[/]' => ['GET'],
        '/{version:latest|dev|v1}/corporations/{corporation_id}/fw/stats[/]' => ['GET'],
        '/{version:latest|dev|v1}/corporations/{corporation_id}/industry/jobs[/]' => ['GET'],
        '/{version:latest|dev|v1}/corporations/{corporation_id}/killmails/recent[/]' => ['GET'],
        '/{version:latest|dev|v1}/corporations/{corporation_id}/shareholders[/]' => ['GET'],
        '/{version:latest|dev|v1}/corporations/{corporation_id}/wallets[/]' => ['GET'],
        '/{version:latest|dev|v1}/corporations/{corporation_id}/wallets/{division}/transactions[/]' => ['GET'],
        '/{version:latest|dev|v1}/dogma/attributes[/]' => ['GET'],
        '/{version:latest|dev|v1}/dogma/attributes/{attribute_id}[/]' => ['GET'],
        '/{version:latest|dev|v1}/dogma/dynamic/items/{type_id}/{item_id}[/]' => ['GET'],
        '/{version:latest|dev|v1}/dogma/effects[/]' => ['GET'],
        '/{version:latest|dev|v1}/fleets/{fleet_id}[/]' => ['GET', 'PUT'],
        '/{version:latest|dev|v1}/fleets/{fleet_id}/members[/]' => ['GET', 'POST'],
        '/{version:latest|dev|v1}/fleets/{fleet_id}/members/{member_id}[/]' => ['DELETE', 'PUT'],
        '/{version:latest|dev|v1}/fleets/{fleet_id}/squads/{squad_id}[/]' => ['DELETE', 'PUT'],
        '/{version:latest|dev|v1}/fleets/{fleet_id}/wings[/]' => ['GET', 'POST'],
        '/{version:latest|dev|v1}/fleets/{fleet_id}/wings/{wing_id}[/]' => ['DELETE', 'PUT'],
        '/{version:latest|dev|v1}/fleets/{fleet_id}/wings/{wing_id}/squads[/]' => ['POST'],
        '/{version:latest|dev|v1}/fw/leaderboards[/]' => ['GET'],
        '/{version:latest|dev|v1}/fw/leaderboards/characters[/]' => ['GET'],
        '/{version:latest|dev|v1}/fw/leaderboards/corporations[/]' => ['GET'],
        '/{version:latest|dev|v1}/fw/stats[/]' => ['GET'],
        '/{version:latest|dev|v1}/fw/wars[/]' => ['GET'],
        '/{version:latest|dev|v1}/incursions[/]' => ['GET'],
        '/{version:latest|dev|v1}/industry/facilities[/]' => ['GET'],
        '/{version:latest|dev|v1}/industry/systems[/]' => ['GET'],
        '/{version:latest|dev|v1}/insurance/prices[/]' => ['GET'],
        '/{version:latest|dev|v1}/killmails/{killmail_id}/{killmail_hash}[/]' => ['GET'],
        '/{version:latest|dev|v1}/loyalty/stores/{corporation_id}/offers[/]' => ['GET'],
        '/{version:latest|dev|v1}/markets/groups[/]' => ['GET'],
        '/{version:latest|dev|v1}/markets/groups/{market_group_id}[/]' => ['GET'],
        '/{version:latest|dev|v1}/markets/prices[/]' => ['GET'],
        '/{version:latest|dev|v1}/markets/structures/{structure_id}[/]' => ['GET'],
        '/{version:latest|dev|v1}/markets/{region_id}/history[/]' => ['GET'],
        '/{version:latest|dev|v1}/markets/{region_id}/orders[/]' => ['GET'],
        '/{version:latest|dev|v1}/markets/{region_id}/types[/]' => ['GET'],
        '/{version:latest|dev|v1}/opportunities/groups[/]' => ['GET'],
        '/{version:latest|dev|v1}/opportunities/groups/{group_id}[/]' => ['GET'],
        '/{version:latest|dev|v1}/opportunities/tasks[/]' => ['GET'],
        '/{version:latest|dev|v1}/opportunities/tasks/{task_id}[/]' => ['GET'],
        '/{version:latest|dev|v1}/route/{origin}/{destination}[/]' => ['GET'],
        '/{version:latest|dev|v1}/sovereignty/campaigns[/]' => ['GET'],
        '/{version:latest|dev|v1}/sovereignty/map[/]' => ['GET'],
        '/{version:latest|dev|v1}/sovereignty/structures[/]' => ['GET'],
        '/{version:latest|dev|v1}/status[/]' => ['GET'],
        '/{version:latest|dev|v1}/ui/openwindow/contract[/]' => ['POST'],
        '/{version:latest|dev|v1}/ui/openwindow/information[/]' => ['POST'],
        '/{version:latest|dev|v1}/ui/openwindow/marketdetails[/]' => ['POST'],
        '/{version:latest|dev|v1}/ui/openwindow/newmail[/]' => ['POST'],
        '/{version:latest|dev|v1}/universe/ancestries[/]' => ['GET'],
        '/{version:latest|dev|v1}/universe/asteroid_belts/{asteroid_belt_id}[/]' => ['GET'],
        '/{version:latest|dev|v1}/universe/bloodlines[/]' => ['GET'],
        '/{version:latest|dev|v1}/universe/categories[/]' => ['GET'],
        '/{version:latest|dev|v1}/universe/categories/{category_id}[/]' => ['GET'],
        '/{version:latest|dev|v1}/universe/constellations[/]' => ['GET'],
        '/{version:latest|dev|v1}/universe/constellations/{constellation_id}[/]' => ['GET'],
        '/{version:latest|dev|v1}/universe/graphics[/]' => ['GET'],
        '/{version:latest|dev|v1}/universe/graphics/{graphic_id}[/]' => ['GET'],
        '/{version:latest|dev|v1}/universe/groups[/]' => ['GET'],
        '/{version:latest|dev|v1}/universe/groups/{group_id}[/]' => ['GET'],
        '/{version:latest|dev|v1}/universe/ids[/]' => ['POST'],
        '/{version:latest|dev|v1}/universe/moons/{moon_id}[/]' => ['GET'],
        '/{version:latest|dev|v1}/universe/planets/{planet_id}[/]' => ['GET'],
        '/{version:latest|dev|v1}/universe/races[/]' => ['GET'],
        '/{version:latest|dev|v1}/universe/regions[/]' => ['GET'],
        '/{version:latest|dev|v1}/universe/regions/{region_id}[/]' => ['GET'],
        '/{version:latest|dev|v1}/universe/schematics/{schematic_id}[/]' => ['GET'],
        '/{version:latest|dev|v1}/universe/stargates/{stargate_id}[/]' => ['GET'],
        '/{version:latest|dev|v1}/universe/stars/{star_id}[/]' => ['GET'],
        '/{version:latest|dev|v1}/universe/structures[/]' => ['GET'],
        '/{version:latest|dev|v1}/universe/system_jumps[/]' => ['GET'],
        '/{version:latest|dev|v1}/universe/systems[/]' => ['GET'],
        '/{version:latest|dev|v1}/universe/types[/]' => ['GET'],
        '/{version:latest|dev|v1}/wars[/]' => ['GET'],
        '/{version:latest|dev|v1}/wars/{war_id}[/]' => ['GET'],
        '/{version:latest|dev|v1}/wars/{war_id}/killmails[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/alliances/{alliance_id}/contacts[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/characters/affiliation[/]' => ['POST'],
        '/{version:latest|dev|v1|v2}/characters/{character_id}/agents_research[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/characters/{character_id}/assets/locations[/]' => ['POST'],
        '/{version:latest|dev|v1|v2}/characters/{character_id}/bookmarks[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/characters/{character_id}/bookmarks/folders[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/characters/{character_id}/contacts[/]' => ['DELETE', 'GET', 'POST', 'PUT'],
        '/{version:latest|dev|v1|v2}/characters/{character_id}/corporationhistory[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/characters/{character_id}/fatigue[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/characters/{character_id}/fittings[/]' => ['GET', 'POST'],
        '/{version:latest|dev|v1|v2}/characters/{character_id}/mail/labels[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/characters/{character_id}/medals[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/characters/{character_id}/notifications/contacts[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/characters/{character_id}/online[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/characters/{character_id}/orders[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/characters/{character_id}/portrait[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/characters/{character_id}/skillqueue[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/characters/{character_id}/standings[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/characters/{character_id}/titles[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/corporations/npccorps[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/corporations/{corporation_id}/assets/locations[/]' => ['POST'],
        '/{version:latest|dev|v1|v2}/corporations/{corporation_id}/contacts[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/corporations/{corporation_id}/divisions[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/corporations/{corporation_id}/facilities[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/corporations/{corporation_id}/icons[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/corporations/{corporation_id}/medals[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/corporations/{corporation_id}/medals/issued[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/corporations/{corporation_id}/members/limit[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/corporations/{corporation_id}/members/titles[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/corporations/{corporation_id}/membertracking[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/corporations/{corporation_id}/orders/history[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/corporations/{corporation_id}/roles[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/corporations/{corporation_id}/roles/history[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/corporations/{corporation_id}/standings[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/corporations/{corporation_id}/starbases[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/corporations/{corporation_id}/starbases/{starbase_id}[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/corporations/{corporation_id}/titles[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/dogma/effects/{effect_id}[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/fw/systems[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/ui/autopilot/waypoint[/]' => ['POST'],
        '/{version:latest|dev|v1|v2}/universe/factions[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/universe/stations/{station_id}[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/universe/structures/{structure_id}[/]' => ['GET'],
        '/{version:latest|dev|v1|v2}/universe/system_kills[/]' => ['GET'],
        '/{version:latest|dev|v1|v2|v3}/alliances/{alliance_id}[/]' => ['GET'],
        '/{version:latest|dev|v1|v2|v3}/characters/{character_id}/blueprints[/]' => ['GET'],
        '/{version:latest|dev|v1|v2|v3}/characters/{character_id}/calendar/{event_id}[/]' => ['GET', 'PUT'],
        '/{version:latest|dev|v1|v2|v3}/characters/{character_id}/clones[/]' => ['GET'],
        '/{version:latest|dev|v1|v2|v3}/characters/{character_id}/mail/labels[/]' => ['GET'],
        '/{version:latest|dev|v1|v2|v3}/characters/{character_id}/planets/{planet_id}[/]' => ['GET'],
        '/{version:latest|dev|v1|v2|v3}/characters/{character_id}/roles[/]' => ['GET'],
        '/{version:latest|dev|v1|v2|v3}/characters/{character_id}/search[/]' => ['GET'],
        '/{version:latest|dev|v1|v2|v3}/corporations/{corporation_id}/alliancehistory[/]' => ['GET'],
        '/{version:latest|dev|v1|v2|v3}/corporations/{corporation_id}/blueprints[/]' => ['GET'],
        '/{version:latest|dev|v1|v2|v3}/corporations/{corporation_id}/containers/logs[/]' => ['GET'],
        '/{version:latest|dev|v1|v2|v3}/corporations/{corporation_id}/orders[/]' => ['GET'],
        '/{version:latest|dev|v1|v2|v3}/universe/names[/]' => ['POST'],
        '/{version:latest|dev|v1|v2|v3}/universe/types/{type_id}/' => ['GET'],
        '/{version:latest|dev|v1|v2|v3|v4}/characters/{character_id}/skills/' => ['GET'],
        '/{version:latest|dev|v1|v2|v3|v4}/corporations/{corporation_id}/members/' => ['GET'],
        '/{version:latest|dev|v1|v2|v3|v4}/corporations/{corporation_id}/structures/' => ['GET'],
        '/{version:latest|dev|v1|v2|v3|v4}/corporations/{corporation_id}/wallets/{division}/journal/' => ['GET'],
        '/{version:latest|dev|v1|v2|v3|v4}/universe/systems/{system_id}/' => ['GET'],
        '/{version:latest|dev|v1|v2|v3|v4|v5}/characters/{character_id}/' => ['GET'],
        '/{version:latest|dev|v1|v2|v3|v4|v5}/characters/{character_id}/assets/' => ['GET'],
        '/{version:latest|dev|v1|v2|v3|v4|v5}/characters/{character_id}/cspa/' => ['POST'],
        '/{version:latest|dev|v1|v2|v3|v4|v5}/characters/{character_id}/notifications/' => ['GET'],
        '/{version:latest|dev|v1|v2|v3|v4|v5}/corporations/{corporation_id}/' => ['GET'],
        '/{version:latest|dev|v1|v2|v3|v4|v5}/corporations/{corporation_id}/assets/' => ['GET'],
        '/{version:latest|dev|v1|v2|v3|v4|v5|v6}/characters/{character_id}/wallet/journal/' => ['GET'],
        '/{version:latest|dev|v1|v2|v3|v4|v5|v6}/{route:.+}' => ['GET', 'POST', 'PUT', 'DELETE']
    ];

    // Version is always going to be there, but there might be multiple vars after that, use ... to catch them all
    public function handle(string $version, ...$args): ResponseInterface
    {
        $path = $this->request->getUri()->getPath();
        $query = $this->request->getQueryParams();
        // Sort the query params so caching is the same regardless of how the query is sorted
        ksort($query);
        $requestMethod = $this->request->getMethod();
        $body = $this->request->getBody()->getContents();
        $requestBody = $body !== 'php://memory' ? $body : '';

        dump($path, $query, $requestMethod, $requestBody, $version, $args);
        return $this->json(['status' => 'OK']);
    }
}
