namespace: evekill
imagePullPolicy: Always

ingress:
  clusterIssuer: letsencrypt
  ingressClass: nginx
  hostname: eve-kill.com
  tls:
    secretName: evekill-tls

frontend:
  image: ghcr.io/eve-kill/frontend
  version: latest
  replicas: 1

server:
  image: ghcr.io/eve-kill/killboard
  version: latest
  replicas: 1
  hpa:
    minReplicas: 1
    maxReplicas: 1
    cpuUtilization: 80 # The amount of CPU that the deployment should be using, before it is scaled up.
  resources:
    limits:
      enabled: false
      cpu: 2000m
      memory: 2048Mi
    requests:
      enabled: false
      cpu: 1000m
      memory: 1024Mi

queue:
  image: ghcr.io/eve-kill/killboard
  version: latest
  replicas: 1
  hpa:
    minReplicas: 1
    maxReplicas: 1
    cpuUtilization: 80 # The amount of CPU that the deployment should be using, before it is scaled up.
  resources:
    limits:
      enabled: false
      cpu: 2000m
      memory: 2048Mi
    requests:
      enabled: false
      cpu: 1000m
      memory: 1024Mi

cronjob:
  image: ghcr.io/eve-kill/killboard
  version: latest
  schedule: "* * * * *"
  restartPolicy: Never
  startingDeadlineSeconds: 3600
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  resources:
    limits:
      enabled: false
      cpu: 2000m
      memory: 1024Mi
    requests:
      enabled: false
      cpu: 500m
      memory: 512Mi

redisq:
  image: ghcr.io/eve-kill/killboard
  version: latest
  resources:
    limits:
      enabled: false
      cpu: 2000m
      memory: 1024Mi
    requests:
      enabled: false
      cpu: 500m
      memory: 512Mi

redis:
  enabled: true
  maxmemory: 16384mb
  maxmemoryPolicy: allkeys-lru
  resources:
    limits:
      enabled: false
      cpu: 1000m
      memory: 1024Mi
    requests:
      enabled: true
      cpu: 500m
      memory: 512Mi

mongodb:
  enabled: true
  architecture: replicaset
  directoryPerDB: true
  auth:
    enabled: false
  replicaSetName: rs0
  replicaCount: 3
  persistence:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 400Gi
  resources:
    limits:
      memory: 32Gi
    requests:
      cpu: 500m
      memory: 1024Mi
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: true
